# SPDX-License-Identifier: GPL-2.0-only

rockchip-iep-common-objs := iep-common.o
rockchip-iep-objs := iep.o

obj-$(CONFIG_VIDEO_ROCKCHIP_IEP_COMMON) += rockchip-iep-common.o
rockchip-iep2-objs := iep2.o

obj-$(CONFIG_VIDEO_ROCKCHIP_IEP) += rockchip-iep.o
obj-$(CONFIG_VIDEO_ROCKCHIP_IEP2) += rockchip-iep2.o
